services:
  safe-box-bot:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: safe-box-bot
    restart: unless-stopped
    env_file:
      - ./prod.env
    environment:
      IS_DOCKERIZED: "true"
    volumes:
      - ../data/bot.db:/app/data
      - ../data/prompt:/app/data/prompt
    working_dir: /app
